#!/usr/bin/env ruby

require 'json'
require 'net/https'

module JIRA
  class HttpClient
    DEFAULT = {
      :site => "https://*******.atlassian.net",
      :path => "rest/api/latest/issue",
      :ticket_number => "",
      :resource => "",
      :username => "",
      :password => "",
      :use_ssl => true,
      :verify_mode => OpenSSL::SSL::VERIFY_NONE
    }

    attr_reader :options

    def initialize(options)
      @options = DEFAULT.merge(options)
    end

    def uri
       URI.parse "#{@options[:site]}/#{@options[:path]}/#{@options[:ticket_number]}/#{@options[:resource]}"
    end

    def make_request(http_method, body='', header={})
      request_data = Net::HTTP.const_get(http_method.to_s.capitalize).new(uri.request_uri, header)
      request_data.body = body unless body.nil?
      request_data.basic_auth(@options[:username], @options[:password])
      # send request data to jira rest api
      http_conn.request request_data
    end

    def http_conn
      http_conn  = Net::HTTP.new uri.host, uri.port
      http_conn.use_ssl = @options[:use_ssl]
      http_conn.verify_mode = @options[:verify_mode]
      http_conn
    end
  end
end

def header
  { "content-type" => "application/json" }
end

TICKET_REGEXP = /[A-Z]+-\d+/    # WEB-12345

# get current branch name
cur_br_name = %x{git branch}.split("\n").select { |i| i[0] == "*" }.first.gsub("* ", "")

# get ticket number
ticket_number = cur_br_name.match(TICKET_REGEXP).to_s

#puts "first step: push #{current_branch_name} to origin"
#push_branch_to_remote(current_branch_name)


puts "update #{ticket_number} status from 'Start Progress' to 'In Progess'"

jira_configs = %x{git config --list}.split("\n").select do |config|
  config.match('jira.username') or config.match("jira.password")
end

if jira_configs.length != 2
  puts "you did not set username or password in your git config"
  puts "please go to your jira to change status from Open to In Progess"
else
  jira_info = jira_configs.inject({})  do |hash, arr|
    tmp = arr.split("=")
    hash.merge Hash[*tmp]
  end #{ "jira.username" => "your username", "jira.password" => "your password"}

  options = {
    :ticket_number => ticket_number,
    :resource      => "transitions",
    :username      => jira_info["jira.username"],
    :password      => jira_info["jira.password"]
  }

  body = JSON.generate(
   {"update" =>
    { "comment" =>
      [{ "add" =>
         { "body" => "begin to work"}
        }]
    },
    "fields" => {
        "assignee" => {
            "name" => jira_info["jira.username"]
        }
#        "resolution": {
#            "name": "Fixed"
#        }
    },
    "transition" => {
        "id" => "11"
    }

  })

  JIRA::HttpClient.new(options).make_request('post', body, header)
end

